---
pattern_list:
- pattern: "^/mypost$"
  method: POST
  latency: 2000
  response:
    body: Hello, post!
    headers:
      Content-Type: text/plain; charset=utf-8
    status_code: 200
- pattern: "^/mylink$"
  response: ${link(var("some_link"))}
- pattern: "^/myfile$"
  response:
    body: ${file("./main.go")}
    headers:
      Content-Type: ${var("default_content_type")}
      Content-Language: ${if(contains(http_header("Accept-Language"), "en")) "en"
        else "it"}
      Cache-Control: ${http_header("Cache-Control")}
    status_code: 200
- pattern: "^/myredirect$"
  response: ${redirect("http://localhost:8080/111")}
- pattern: "^/[a-z]+$"
  response:
    body: Hello, string!
    headers:
      Content-Type: text/plain; charset=utf-8
    status_code: 200
- pattern: "^/[0-9]+$"
  response:
    body: Hello, number!
    headers:
      Content-Type: text/plain; charset=utf-8
      X-Test: some additional header
    status_code: 404
- pattern: "^.*$"
  response:
    body: Hello, default body!
    status_code: 200
options:
  enable_cors: true
vars:
  some_link: http://localhost:8080/aaa
  default_content_type: text/plain; charset=utf-8